# Scratchpad terminal (foot)
for_window [app_id="foot-scratchpad"] move to scratchpad, floating enable, border normal 4, resize set 900 500, move position center
for_window [app_id="cheatsheet"] move to scratchpad, floating enable, resize set 900 900, move position center
