exec_always foot --app-id cheatsheet sh -c "bat ~/.config/sway/shortcuts.md"
exec python3 ~/.config/theme/generate-theme.py
exec_always python /usr/share/sway-contrib/inactive-windows-transparency.py
exec_always python /usr/share/sway-contrib/layout-per-window.py
