# --- Window Decorations ---
# class                 border       backgr.      text         indicator    child_border
client.focused          $main_border  $bg     $text_bright $text_special  $main_border 
client.focused_inactive $main_border  $bg     $text_muted  $bg    $main_border
client.unfocused        $dark_purple  $bg     $text_muted  $bg     $dark_purple

# --- Sizing & Gaps ---
default_border pixel 4
default_floating_border pixel 4
gaps inner 10
gaps outer 5
smart_gaps off

# --- Font ---
font pango:Terminus 11

### Output configuration
#
# Default wallpaper (more resolutions are available in /usr/share/backgrounds/sway/)
output * bg #1f1a2d solid_color
