# 1 - Games / fullscreen
assign [app_id="steam"] $ws1
assign [app_id="lutris"] $ws1
assign [app_id="gamescope"] $ws1

# 2 - Main
assign [app_id="firefox"] $ws2

# 3 - Terminal
assign [app_id="foot"] $ws3

# 4 - Discord
assign [app_id="discord"] $ws4
assign [app_id="vesktop"] $ws4

# 5 - Spotify
assign [app_id="spotify"] $ws5
assign [class="Spotify"] $ws5
