set $bg      #1f1a2d 
set $main_border      #1f1a2d
set $dark_purple  #161022
set $light_purple #2d2735
set $pop_border    #284dff
set $text_special    #00dbff
set $text_muted   #888888
set $text_bright  #ffffff
